Repository drone/docs, pull requests merged in 2018-02, with the labels that each got.

#314 Set text/html for files w/o extension
  .drone.yml
Labels: bug

#311 mention that you can horizontally scale by adding agents
  content/install/installation_overview.md
Labels: topic/installation

#315 Try to make the global secret/registry docs more consistent
  content/install/extensions/global_registries.md
  content/install/extensions/global_secrets.md
  content/install/extensions/integrate_vault.md
  content/usage/secrets/registries_global.md
  content/usage/secrets/secrets.md
  content/usage/secrets/secrets_global.md
  content/usage/secrets/secrets_vault.md
Labels: topic/installation, topic/usage

#318 Add page_meta partial to other pages
  themes/drone/layouts/api/single.html
  themes/drone/layouts/cli/single.html
  themes/drone/layouts/install/single.html
  themes/drone/layouts/plugin/single.html
Labels: enhancement, usability

#320 More agent info
  content/install/installation_overview.md
Labels: enhancement
